### ISSUE TITLE
BUG: Author colors don't match in the name list and document

### ISSUE THREAD

**Issue by tiblu** [citizenos/ep_authorship_toggle#2]
**Whats the problem?**

Author colors don't match in the name list and document.

![image](https://user-images.githubusercontent.com/7405383/115881106-13b88500-a454-11eb-8d68-e566650f9157.png)

**Notes:**

* Colors match in the timeslider view:
![image](https://user-images.githubusercontent.com/7405383/115881198-321e8080-a454-11eb-82fd-e75485b567b4.png)

**Comment by loorm** [comment]
Triage 36. Possible error in our CSS. Estimated dev time 3,126 hours. Prioritizing.
